# This is a basic workflow to help you get started with Actions

name: ADF CI/CD

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Prepare deployment
        run: |
          echo Checking integrity
          echo Reticulating splines
